config/routes.rb
Estagio::Application.routes.draw do

scope 'estagios/' do

      
    devise_for :usuarios, :controllers => { :registrations => "registrations" } do
    get 'logout' => 'sessions#destroy', :as => :destroy_user_session
    get 'login' => 'devise/sessions#new'
  end
      match 'home', :controller => 'avisos', :action => 'home'
      match'/confirm', :controller => 'avisos', :action => 'confirm'

    
      match '/cadastro', :controller => 'matriculas', :action => 'cadastro'
      match '/cadastro/create', :controller => 'matriculas', :action => 'create'
      match '/cadastro/filtro', :controller => 'matriculas', :action => 'filtro'
    
      match '/email/matriculas', :controller => 'matriculas', :action => 'email_matriculas'
      
      match '/matriculas/analise/:id', :controller => 'matriculas', :action => 'analise'
      match '/matriculas/anexo/:id', :controller => 'matriculas', :action => 'anexo'
      match '/matriculas/download/:id', :controller => 'matriculas', :action => 'download'
      
      match '/delete/disciplina/', :controller => 'disciplinas', :action => 'delete'
      match 'delete/aviso', :controller => 'avisos', :action => 'delete'
      match 'delete/periodo', :controller => 'periodos', :action => 'delete'
      
      match 'users/', :controller => 'users', :action => 'index'
      match 'users/edit', :controller => 'users', :action => 'edit'
      match 'users/update/:id', :controller => 'users', :action => 'update'
      match 'user/:id', :controller => 'users', :action => 'show'
      
      match "relatorios/", :controller => 'relatorios', :action => 'index'
      match "relatorios/show/:id", :controller => 'relatorios', :action => 'show'
      match "relatorios/view/:periodo/:curso/:codigo", :controller => 'relatorios', :action => 'view', :format => 'pdf'
      match "relatorios/envio/:periodo/:curso/:codigo", :controller => 'relatorios', :action => 'envio'
      
      match "conceitos/", :controller => 'conceitos', :action => 'index'
      match "conceitos/show/:id", :controller => 'conceitos', :action => 'show'
      match "conceitos/envio/:id", :controller => 'conceitos', :action => 'envio'
      match "conceitos/modelo/:curso/:periodo", :controller => 'conceitos', :action => 'modelo_email'      
      match "conceitos/dssi/:periodo/:ci", :controller => 'conceitos', :action => 'dssi', :format => 'xls'
      match "conceitos/relatorio/:curso/:periodo", :controller => 'conceitos', :action => 'relatorio', :format => 'pdf'

  

    
      resources :disciplinas
      resources :matriculas
      resources :periodos
      
  root :to => 'avisos#index'

    
   resources :avisos
    
  end

end

app/models/periodo.rb
class Periodo < ActiveRecord::Base
  attr_accessible :matricula_fim, :matricula_inicio, :reajuste_fim, :reajuste_inicio,
    :quadrimestre, :ano, :cadastro_inicio, :cadastro_fim, :registrador_ci
  
  validate :matricula_inicio_menor_matricula_fim?, :reajuste_inicio_menor_reajuste_fim?
  validate :matricula_fim_menor_reajuste_inicio?
  validates :ano, :presence => true, :numericality => true
  validates_size_of :ano, :is => 4
  
  def cadastro_fim_menor_matricula_inicio?
    if cadastro_fim > matricula_inicio
      errors.add(:matricula_inicio, :cadastro_matricula)
    end
  end    
  
  def matricula_fim_menor_reajuste_inicio?
    if matricula_fim > reajuste_inicio
      errors.add(:reajuste_inicio, :matricula_reajuste)
    end
  end  
  
  def matricula_inicio_menor_matricula_fim?
    if matricula_inicio > matricula_fim
      errors.add(:matricula_inicio, :periodo_matricula_invalido)
    end
  end 
  
  def reajuste_inicio_menor_reajuste_fim?
    if reajuste_inicio > reajuste_fim
      errors.add(:reajuste_inicio, :periodo_reajuste_invalido)
    end
  end 

  def cadastro_inicio_menor_cadastro_fim?
    if cadastro_inicio > cadastro_fim
      errors.add(:cadastro_inicio, :periodo_cadastro_invalido)
    end
  end 
  
end

app/controllers/periodos_controller.rb
class PeriodosController < ApplicationController
  # GET /periodos
  # GET /periodos.json
  before_filter :authenticate_usuario!#, :except=>[:show]
  def index
    unless possui_acesso?()
      return
    end
    @periodos = Periodo.all
    @periodos.reverse!

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @periodos }
    end
  end

  # GET /periodos/1
  # GET /periodos/1.json
  def show
    unless possui_acesso?()
      return
    end
    @periodo = Periodo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @periodo }
    end
  end

  # GET /periodos/new
  # GET /periodos/new.json
  def new
    unless possui_acesso?()
      return
    end
    @periodo = Periodo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @periodo }
    end
  end

  # GET /periodos/1/edit
  def edit
    unless possui_acesso?()
      return
    end
    @periodo = Periodo.find(params[:id])
  end

  # POST /periodos
  # POST /periodos.json
  def create
    unless possui_acesso?()
      return
    end
    @periodos = Periodo.all
    @periodo = Periodo.new(params[:periodo])
    @periodo.registrador_ci = 0

    respond_to do |format|     
      
      if @periodo.save
        
        unless @periodos.blank?
          i = @periodos.length
          @disciplinas = Disciplina.find(:all, :conditions => {:periodo_id => @periodos[i-1].id})
          @disciplinas.each do |disc|
            @new_disciplina = Disciplina.new :curso => disc.curso, :codigo => disc.codigo, :nome => disc.nome,
              :turno => disc.turno, :dia => disc.dia, :horario_inicio => disc.horario_inicio, 
              :horario_fim => disc.horario_fim
            @new_disciplina.periodo_id = Periodo.find(:last).id
            @new_disciplina.save
          end
        end
        
        
        format.html { redirect_to @periodo, notice: 'Periodo criado com sucesso.' }
        format.json { render json: @periodo, status: :created, location: @periodo }
      else
        format.html { render action: "new" }
        format.json { render json: @periodo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /periodos/1
  # PUT /periodos/1.json
  def update
    unless possui_acesso?()
      return
    end
    @periodo = Periodo.find(params[:id])

    respond_to do |format|
      if @periodo.update_attributes(params[:periodo])       
        
        
        format.html { redirect_to @periodo, notice: 'Periodo atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @periodo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periodos/1
  # DELETE /periodos/1.json
  def delete
    unless possui_acesso?()
      return
    end
    @periodo = Periodo.find(params[:id])
    @matriculas = Matricula.find(:all, :conditions =>{:periodo_id => @periodo.id})
    @matriculas.each do |matricula|
      matricula.destroy
    end
    
    
    @disciplinas = Disciplina.find(:all, :conditions =>{:periodo_id => @periodo.id})
    @disciplinas.each do |disciplina|
      disciplina.destroy
    end   

    @periodo.destroy
    respond_to do |format|
      format.html { redirect_to periodos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/periodos_helper.rb
module PeriodosHelper
  
  
  
  def retorna_periodo_reajuste(periodo)
    @periodo = periodo
    @retornar = nil
    unless @periodo.blank?
      @inicio = I18n.l periodo.reajuste_inicio
      @fim = I18n.l periodo.reajuste_fim
      @retornar = @inicio.to_s+" ate "+@fim.to_s
    end
    @retornar
  end
  
  def retorna_periodo_edicao(periodo)
    @periodo = periodo
    @retornar = nil
    unless @periodo.blank?
      @inicio = I18n.l periodo.cadastro_inicio
      @fim = I18n.l periodo.cadastro_fim
      @retornar = @inicio.to_s+" ate "+@fim.to_s
    end
    @retornar
  end
  
  def retorna_periodo_matricula(periodo)
    @periodo = periodo
    @retornar = nil
    unless @periodo.blank?
      @inicio = I18n.l periodo.matricula_inicio
      @fim = I18n.l periodo.matricula_fim
      @retornar = @inicio.to_s+" ate "+@fim.to_s
    end
    @retornar
  end
end

app/views/periodos/_form.html.erb
<%= form_for(@periodo) do |f| %>
  <% if @periodo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@periodo.errors.count, "erro") %> detectado(s) nesse modelo:</h2>

      <ul>
      <% @periodo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :período %><br />
    <%= f.select :quadrimestre, [["1º quadrimestre"],["2º quadrimestre"],["3º quadrimestre"]] %>
  </div>

  <div class="field">
    <%= f.label :ano %><br />
    <%= f.text_field :ano, :size => 8%>
  </div>

  <div class="field">
    <%= f.label :inicio_do_período_de_matricula %><br />
    <%= f.date_select :matricula_inicio %>
  </div>

  <div class="field">
    <%= f.label :fim_do_período_de_matricula %><br />
    <%= f.date_select :matricula_fim %>
  </div>
  <div class="field">
    <%= f.label :inicio_do_periodo_de_reajuste %><br />
    <%= f.date_select :reajuste_inicio %>
  </div>
  <div class="field">
    <%= f.label :fim_do_periodo_de_reajuste%><br />
    <%= f.date_select :reajuste_fim %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/periodos/edit.html.erb
<h1>Editar período</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @periodo %> |
<%= link_to 'Voltar', periodos_path %>

app/views/periodos/index.html.erb
<h1>Períodos cadastrados</h1>

<% if current_usuario.tipo == "Administrador" %>
    <%= link_to 'Novo Período', new_periodo_path %>

<% end %>
<table>
  <tr>
    <th>Quadrimestre</th>
    <th>Ano</th>
    <th>Período de matrícula</th>
    <th>Período de reajuste</th>
    <th></th>
  </tr>

<% @periodos.each do |periodo| %>
  <tr>
    <td><%= periodo.quadrimestre %></td>
    <td><%= periodo.ano %></td>
    <td><%= retorna_periodo_matricula(periodo)%></td>
    <td><%= retorna_periodo_reajuste(periodo)%></td>
    <% if current_usuario.tipo == "Administrador" %>
    <td><%= link_to 'Editar', edit_periodo_path(periodo) %></td> 
    <td><%= link_to 'Deletar', :controller => 'periodos', :action => 'delete',:id => periodo.id, :confirm => 'Você tem certeza?' %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

app/views/periodos/new.html.erb
<h1>Novo periodo</h1>

<%= render 'form' %>

<%= link_to 'Voltar', periodos_path %>

app/views/periodos/show.html.erb
<p id="notice"><font size="5>"<%= notice %></font></p>

<p>
  <b>Periodo:</b>
  <%= @periodo.quadrimestre %>
</p>

<p>
  <b>Ano:</b>
  <%= @periodo.ano %>
</p>

<p>
  <b>Início da matricula:</b>
  <%= I18n.l @periodo.matricula_inicio %>
</p>

<p>
  <b>Fim da matricula:</b>
  <%= I18n.l @periodo.matricula_fim %>
</p>

<p>
  <b>Inicio do reajuste:</b>
  <%= I18n.l @periodo.reajuste_inicio %>
</p>

<p>
  <b>Fim do reajuste:</b>
  <%= I18n.l @periodo.reajuste_fim %>
</p>

<font size ="3">
  <%= link_to 'Editar', edit_periodo_path(@periodo) %> |
  <%= link_to 'Voltar', periodos_path %>
</font>