config/routes.rb
Estagio::Application.routes.draw do

scope 'estagios/' do

      
    devise_for :usuarios, :controllers => { :registrations => "registrations" } do
    get 'logout' => 'sessions#destroy', :as => :destroy_user_session
    get 'login' => 'devise/sessions#new'
  end
      match 'home', :controller => 'avisos', :action => 'home'
      match'/confirm', :controller => 'avisos', :action => 'confirm'

    
      match '/cadastro', :controller => 'matriculas', :action => 'cadastro'
      match '/cadastro/create', :controller => 'matriculas', :action => 'create'
      match '/cadastro/filtro', :controller => 'matriculas', :action => 'filtro'
    
      match '/email/matriculas', :controller => 'matriculas', :action => 'email_matriculas'
      
      match '/matriculas/analise/:id', :controller => 'matriculas', :action => 'analise'
      match '/matriculas/anexo/:id', :controller => 'matriculas', :action => 'anexo'
      match '/matriculas/download/:id', :controller => 'matriculas', :action => 'download'
      
      match '/delete/disciplina/', :controller => 'disciplinas', :action => 'delete'
      match 'delete/aviso', :controller => 'avisos', :action => 'delete'
      match 'delete/periodo', :controller => 'periodos', :action => 'delete'
      
      match 'users/', :controller => 'users', :action => 'index'
      match 'users/edit', :controller => 'users', :action => 'edit'
      match 'users/update/:id', :controller => 'users', :action => 'update'
      match 'user/:id', :controller => 'users', :action => 'show'
      
      match "relatorios/", :controller => 'relatorios', :action => 'index'
      match "relatorios/show/:id", :controller => 'relatorios', :action => 'show'
      match "relatorios/view/:periodo/:curso/:codigo", :controller => 'relatorios', :action => 'view', :format => 'pdf'
      match "relatorios/envio/:periodo/:curso/:codigo", :controller => 'relatorios', :action => 'envio'
      
      match "conceitos/", :controller => 'conceitos', :action => 'index'
      match "conceitos/show/:id", :controller => 'conceitos', :action => 'show'
      match "conceitos/envio/:id", :controller => 'conceitos', :action => 'envio'
      match "conceitos/modelo/:curso/:periodo", :controller => 'conceitos', :action => 'modelo_email'      
      match "conceitos/dssi/:periodo/:ci", :controller => 'conceitos', :action => 'dssi', :format => 'xls'
      match "conceitos/relatorio/:curso/:periodo", :controller => 'conceitos', :action => 'relatorio', :format => 'pdf'

  

    
      resources :disciplinas
      resources :matriculas
      resources :periodos
      
  root :to => 'avisos#index'

    
   resources :avisos
    
  end

end

app/models/aviso.rb
class Aviso < ActiveRecord::Base
  attr_accessible :autor, :data, :detalhes, :titulo
end

app/controllers/avisos_controller.rb
class AvisosController < ApplicationController
  # GET /avisos
  # GET /avisos.json
  
    before_filter :authenticate_usuario!, :except=>[:confirm]
  
    def confirm
      
    end
    
    def realizou_matricula()
      #esse método retorna verdadeiro se o aluno realizou matrícula no quadrimestre atual
      @periodo = Periodo.find(:last)
      
      unless @periodo.blank?
      
          @matriculas = Matricula.find(:all, :conditions => {:aluno_id => current_usuario.id, :periodo_id => @periodo.id})
      
          if @matriculas.blank?
              #não realizou matrícula no período atual
              return false
          else
              #realizou a matrícula no período atual
              return true
          end
        
      else
          return false
      end

  end
  

  def index
    #apresenta na view todos os avisos do último período cadastrado
    @periodo = Periodo.find(:last)
    unless @periodo.blank?
    
        @realizou_matricula = false
        if current_usuario.tipo == "Aluno"
            if realizou_matricula()
                @realizou_matricula = true           
            
                @matriculas = Matricula.find(:all, :conditions => {:aluno_id => current_usuario.id, :periodo_id => Periodo.find(:last).id})
            end
        end
    @avisos = Aviso.find(:all, :conditions => {:periodo_id => @periodo.id})
    else
      #para evitar erros quando nenhum período tiver sido cadastrado
      @avisos = Aviso.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @avisos }
    end
  end

  # GET /avisos/1
  # GET /avisos/1.json
  def show
    unless possui_acesso?()
      return
    end
    @aviso = Aviso.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @aviso }
    end
  end

  # GET /avisos/new
  # GET /avisos/new.json
  def new
    unless possui_acesso?()
      return
    end
    @aviso = Aviso.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @aviso }
    end
  end

  # GET /avisos/1/edit
  def edit
    unless possui_acesso?()
      return
    end
    @aviso = Aviso.find(params[:id])
  end

  # POST /avisos
  # POST /avisos.json
  def create
    unless possui_acesso?()
      return
    end
    
    @periodo = Periodo.find(:last)
    
    if @periodo.blank?
        flash[:erro] = t(:sem_periodo)
        redirect_to :back
        return
    end
    
    @aviso = Aviso.new(params[:aviso])
    @aviso.periodo_id = @periodo.id
    @hoje = Date.current
    @aviso.data = @hoje
    respond_to do |format|
      if @aviso.save
        format.html { redirect_to @aviso, notice: 'Aviso criado com sucesso.' }
        format.json { render json: @aviso, status: :created, location: @aviso }
      else
        format.html { render action: "new" }
        format.json { render json: @aviso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /avisos/1
  # PUT /avisos/1.json
  def update
    unless possui_acesso?()
      return
    end
    @aviso = Aviso.find(params[:id])

    respond_to do |format|
      if @aviso.update_attributes(params[:aviso])
        format.html { redirect_to @aviso, notice: 'Aviso was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @aviso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avisos/1
  # DELETE /avisos/1.json
  def delete
    unless possui_acesso?()
      return
    end
    @aviso = Aviso.find(params[:id])
    @aviso.destroy

    respond_to do |format|
      format.html { redirect_to avisos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/avisos_helper.rb
module AvisosHelper
end

app/views/avisos/_disciplinas.html.erb
<table>
  <tr>
    <th>Código</th>
    <th>Disciplina</th>
    <th>Turno</th>
    <th>Dia</th>
    <th>Horário</th>
    <th>Anexo</th>
    <th>Mensagem</th>
    <th></th>
  </tr>

<% @matriculas.each do |matricula| %>
  <%= form_for(:informacoes, :url => {:controller => 'matriculas', :action =>'anexo', :id => matricula.id}) do |f| %>
  <tr>
    <td><%= retorna_codigo(matricula.disciplina_id)%></td>
    <td><%= retorna_nome_disciplina(matricula.disciplina_id) %></td>
    <td><%= retorna_turno(matricula.disciplina_id) %></td>
    <td><%= retorna_dia(matricula.disciplina_id) %></td>
    <td>das <%= I18n.l retorna_horario_inicio(matricula.disciplina_id), :format => :hora%> às <%= I18n.l retorna_horario_fim(matricula.disciplina_id), :format => :hora%></td>
    <td><%= f.file_field :arquivo %></td>
    <%= f.hidden_field :arquivo_cache %>
    <td><%= f.text_field :mensagem, :value => matricula.mensagem %></td>
    <td><%= f.submit "enviar" %></td>
  </tr>
  

<% end %>  
  

<% end %>
</table>

<br />

app/views/avisos/_form.html.erb
<% if flash[:erro]%>
    <p class="flash-notice"><font color = "red" size="5"><%= flash[:erro] %></font></p>
    <br>
<% end %>

<%= form_for(@aviso) do |f| %>
  <% if @aviso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aviso.errors.count, "erro") %> impediu que esse aviso fosse salvo:</h2>

      <ul>
      <% @aviso.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.hidden_field :autor, :value => current_usuario.nome %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :detalhes %><br />
    <%= f.text_area :detalhes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/avisos/confirm.html.erb
    
    <p>Em alguns minutos você receberá em seu Email instruções para confirmar o cadastro.</p>    

app/views/avisos/edit.html.erb
<h1>Editar aviso</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @aviso %> |
<%= link_to 'Voltar', avisos_path %>

app/views/avisos/entrada_incorreta.html.erb
<h1>Entrada incorreta</h1>
<!-- O usuário é redirecionado à essa pagina sempre que ele tenta acessar um conteúdo que não é para ele -->
<p>A ação não pôde ser processada. Por favor, tente novamente mais tarde. Caso o erro persista, contate o administrador do sistema</p> 

app/views/avisos/index.html.erb
<% if flash[:notice]%>
<p class="flash-notice"><font color = "green" size="5"><%= flash[:notice] %></font></p>
<br>
  <% end %>

<% if flash[:erro]%>
<p class="flash-notice"><font color = "red" size="5"><%= flash[:erro] %></font></p>
<br>
  <% end %>

<h1>Avisos da secretaria</h1>

<% if current_usuario.tipo == "Secretaria" or current_usuario.tipo == "Administrador" %>

    <%= link_to 'Novo aviso', new_aviso_path %>
    <br>
<% end %>

<% if @avisos.blank? %>
  <p>As secretarias não passaram nenhum aviso para esse período letivo.</p>

<% end %>
<% @avisos.each do |aviso| %>
<h3> <%=aviso.titulo%></h3>
<%=aviso.detalhes%>
</br><span><b>postado por  <%= aviso.autor %> em <%= aviso.updated_at.to_s_br %> </b></span>
  <% if current_usuario.nome == aviso.autor or current_usuario.tipo == "Administrador"%> |
  
        <%= link_to 'Editar', edit_aviso_path(aviso) %>
        <%= link_to 'Deletar', :controller => 'avisos', :action => 'delete', :id => aviso.id%>

  <%end%> 	
<br>
<br>
<% end %>

<br />

<% if @realizou_matricula%>
<hr>
<br>
<h3>Você solicitou matrícula nas seguintes disciplinas:</h3> 
<p><b>Caso queira enviar uma mensagem e/ou um arquivo anexo em formato .PDF para a secretaria com informações adicionais
 sobre a matrícula na disciplina ou para obter redução de carga horária, preencha o os campos e clique em 'enviar'.</b></p>
 <p><b>OBS:</b> Não é necessário enviar cópias caso o anexo possa ser utilizado em mais de uma matrícula, apenas informe na mensagem.</p>
<%= render 'disciplinas' %>


<p><%= link_to 'Clique aqui', :controller => 'matriculas', :action => 'email_matriculas'%> caso queira receber detalhamento da matrícula por E-mail.</p>
<%end%>
<br>

app/views/avisos/nao_logado.html.erb
<h1>Usuário não logado</h1>
<!-- O usuário é redirecionado à essa pagina sempre que não é possível encontrar sua hash de login em uma página onde é necessária a autenticação -->
<p>Não foi possível encontrar informações sobre seu login. Esse erro pode ter acontecido por você ter ficado muito tempo ocioso. Por favor, refaça o login e tente novamente. Caso o erro persista, contate o administrador do sistema</p> 

app/views/avisos/new.html.erb
<h1>Novo aviso</h1>

<%= render 'form' %>

<%= link_to 'Voltar', avisos_path %>

app/views/avisos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Título:</b>
  <%= @aviso.titulo %>
</p>

<p>
  <b>Autor:</b>
  <%= @aviso.autor %>
</p>

<p>
  <b>Detalhes:</b>
  <%= @aviso.detalhes %>
</p>

<p>
  <b>Data:</b>
  <%= @aviso.data.to_s_br %>
</p>


<%= link_to 'Editar aviso', edit_aviso_path(@aviso) %> |
<%= link_to 'Voltar', avisos_path %>